name: Build and Test Git-Semver Tool

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'

      - name: Setup git-semver
        uses: DJ-BBot/setup-git-semver@27972e275f4e87726270df48dec96af0ce64efa5 # v1.0.0
        with:
          version: 'latest'

      - name: Test git-semver
        run: |
          git-semver